if [ -n "${SEARCH_RUNTIME_TEST_CONFIG_SOURCE:-}" ]; then
    export DEEPEYES_V2_SEARCH_CONFIG_PATH="${SEARCH_RUNTIME_TEST_CONFIG_SOURCE}"
else
    unset DEEPEYES_V2_SEARCH_CONFIG_PATH
fi
export SEARCH_RUNTIME_TEST_SEARCH_AUTH="${SEARCH_RUNTIME_TEST_TOKEN}"
export BRAVE_SEARCH_API_KEY="${SEARCH_RUNTIME_TEST_UNRELATED_TOKEN}"
set -x
