import config from '../../ci/config.json' with { type: 'json' };
import { runCommand } from './runs.mjs';

function parseCommand(body) {
  const attribution =
    /\n\s*<div align="right">\s*<sup>This reply was automatically generated by <code>@[\w-]+<\/code>\.<\/sup>\s*<\/div>$/;
  const text = body.trim().replace(attribution, '').trim();
  const match = text.match(/^\/(rerun|cancel|help)(?:[ \t]+([^\r\n]*))?$/);
  return match ? { name: match[1], args: (match[2] || '').trim() } : null;
}

function help() {
  const targets = Object.entries(config.targets)
    .map(([name, target]) => `| \`${name}\` | ${target.job || target.workflow} |`)
    .join('\n');
  return [
    '## CI commands',
    '',
    '- `/rerun [failed|all|target]`: rerun failed jobs by default, or a selected workflow/check.',
    '- `/cancel <workflow|all>`: cancel entire workflows, including their matrix jobs.',
    '- `/help`: show this help.',
    '- `/bypass <workflow|all>`: CI team exemption, evaluated by ShigureLab/ci-bypass on a workflow run.',
    '- `/review`: request Nyanpasu review.',
    '',
    'Rerun/cancel require PR authorship or repository write access. Post one command per comment.',
    '',
    '| Target | Check / workflow |',
    '| --- | --- |',
    targets,
  ].join('\n');
}

export async function run({ github, context, core }) {
  const { payload, repo } = context;
  const comment = payload.comment;
  if (!payload.issue?.pull_request || payload.action !== 'created' || !comment) return;
  if (comment.user.type === 'Bot') return;
  const command = parseCommand(comment.body);
  if (!command) return;

  const number = payload.issue.number;
  const { data: pr } = await github.rest.pulls.get({ ...repo, pull_number: number });
  if (pr.state !== 'open') return;
  const marker = `<!-- relax-ci:command:${comment.id} -->`;
  const comments = await github.paginate(github.rest.issues.listComments, {
    ...repo,
    issue_number: number,
    per_page: 100,
  });
  if (comments.some((item) => item.user.type === 'Bot' && item.body.startsWith(marker))) return;

  const runUrl = `${context.serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${context.runId}`;
  // Claim this comment before issuing an Actions API write, including on workflow reruns.
  const { data: reply } = await github.rest.issues.createComment({
    ...repo,
    issue_number: number,
    body: `${marker}\nProcessing /${command.name}. [Workflow run](${runUrl})`,
  });
  let message;
  try {
    if (command.name === 'help') {
      if (command.args) throw new Error('Usage: /help');
      message = help();
    } else {
      if (comment.user.login !== pr.user.login) {
        const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
          ...repo,
          username: comment.user.login,
        });
        if (!['admin', 'maintain', 'write'].includes(data.permission)) {
          throw new Error('Only the PR author or users with write access can rerun or cancel CI.');
        }
      }
      message = await runCommand({
        github,
        repo,
        pr,
        config,
        command: command.name,
        args: command.args,
      });
    }
  } catch (error) {
    core.warning(error.message);
    message = `Command did not complete: ${error.message}`;
  }
  await github.rest.issues.updateComment({
    ...repo,
    comment_id: reply.id,
    body: `${marker}\n${message}\n\n[Workflow run](${runUrl})`,
  });
}
